export const site = {
  name: "Pablo Alejandro López Sánchez",
  shortName: "Pablo López",
  role: "Data & AI Engineer",
  tagline: "Operational complexity, solved with data & AI.",

  /** The five-second version, for the hero. */
  oneLiner:
    "I build forecasting systems, data pipelines and LLM agents that run in production — not in notebooks.",

  /** The longer version, for /about and for meta descriptions. */
  intro: [
    "I'm the data and automation engineer at Mercaldas, a retail grocery chain in Manizales, Colombia — and the only person there who writes code. I built the weekly demand forecast for thousands of product×store series end to end, a market-price intelligence pipeline that turns a hostile public data source into decisions, and a conversational assistant that answers business questions with verified numbers instead of invented ones.",
    "I also build my own infrastructure. Cortana is a personal AI operating system with a plain-text knowledge vault as its long-term memory and a multi-agent runtime that asks me before it does anything it cannot undo.",
    "What I'm looking for now is to apply the same engineering judgment to energy access and distributed generation data — on a team where I'm not the person who knows the most in the room.",
  ],

  url: "https://pablolopez.vercel.app",

  contact: {
    email: "poglolopez@gmail.com",
    linkedin: "https://linkedin.com/in/pablo-a-lopez-s",
    linkedinLabel: "linkedin.com/in/pablo-a-lopez-s",
    github: "https://github.com/PogloLopez",
    githubLabel: "github.com/PogloLopez",
    location: "Manizales, Colombia · open to remote",
  },

  cv: {
    en: "https://github.com/PogloLopez/PogloLopez/raw/main/assets/cv/Pablo-Lopez-CV-EN.pdf",
    es: "https://github.com/PogloLopez/PogloLopez/raw/main/assets/cv/Pablo-Lopez-CV-ES.pdf",
  },
} as const;

/**
 * The headline figures on the home page. Deliberately four, deliberately in
 * ranges: every business number from Mercaldas is published as an order of
 * magnitude or a percentage, never as an exact figure.
 */
export const headlineStats = [
  {
    value: "Thousands",
    label: "Product×store series forecast every week, in production",
  },
  {
    value: "Double digit",
    label: "Percent WMAPE cut against the ERP baseline it replaced",
  },
  {
    value: "5 systems",
    label: "Designed, built and operated end to end — as the sole engineer",
  },
  {
    value: "Zero",
    label: "Business figures generated by a language model without a query behind them",
  },
] as const;
