/**
 * Builds the site's real, interactive demos (src/components/demos) into
 * plain scripts the prototype pages can run, plus the styles they need.
 *
 *   node prototypes/project-pages/build-demos.cjs
 *
 * 1. Copies the demo sources into demos-src/components/, applying the
 *    employer-name renames (the originals still carry repo names like
 *    "mercaldas-data"; NOTES.md lists the same edits for src/).
 * 2. Bundles each demo with React into demos/<slug>.js with esbuild, which is
 *    installed once into a git-ignored .tools folder so the app's own
 *    package.json stays untouched.
 * 3. Compiles the Tailwind utilities those demos use into demos/demos.css,
 *    with the app's own theme tokens, so they look as they do on the site.
 *
 * The outputs are committed: viewing the prototype needs no build step.
 */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const HERE = __dirname;
const REPO = path.resolve(HERE, "..", "..");
const SRC = path.join(REPO, "src", "components", "demos");
const WORK = path.join(HERE, "demos-src");
const OUT = path.join(HERE, "demos");

const DEMOS = {
  forecast: "ForecastDemo",
  "market-prices": "MarketPricesDemo",
  rag: "RagDemo",
  "operations-platform": "OperationsDemo",
  cortana: "CortanaDemo",
};

// The employer is never named. Longest names first, so a shorter one never
// matches inside a longer one.
const RENAMES = [
  ["mercaldas-precios-mercado", "market-prices"],
  ["mercaldas-forecast", "demand-forecast"],
  ["mercaldas-data", "stock-rebalancing"],
  ["mercaldas-rag", "business-data-assistant"],
  ["from DANE or from Mercaldas", "from DANE or from the company"],
];

/* ---- 1. sources ---------------------------------------------------------- */

function copySources() {
  fs.rmSync(WORK, { recursive: true, force: true });
  fs.mkdirSync(path.join(WORK, "components"), { recursive: true });
  const skip = new Set(["DemoSlot.tsx", "registry.ts"]); // Next-only wiring
  for (const f of fs.readdirSync(SRC)) {
    if (skip.has(f) || !/\.(tsx?|js)$/.test(f)) continue;
    let text = fs.readFileSync(path.join(SRC, f), "utf8");
    for (const [from, to] of RENAMES) text = text.split(from).join(to);
    if (/mercaldas/i.test(text)) throw new Error(`${f} still names the employer`);
    const header = `// GENERATED by build-demos.cjs from src/components/demos/${f}. Do not edit.`;
    fs.writeFileSync(path.join(WORK, "components", f), [header, text].join("\n"));
  }
  fs.writeFileSync(
    path.join(WORK, "README.md"),
    [
      "Generated by `build-demos.cjs`: a copy of `src/components/demos` with the",
      "employer-name renames applied, plus one mount entry per demo. Do not edit;",
      "edit the real demos in `src/` and re-run the build.",
      "",
    ].join("\n"),
  );
}

/* ---- 2. bundles ---------------------------------------------------------- */

// esbuild's JS API rather than its CLI: on Windows the CLI goes through a
// shell whose quoting mangled the NODE_ENV define, which pulled in React's
// development build.
function esbuild() {
  const tools = path.join(HERE, ".tools");
  const pkg = path.join(tools, "node_modules", "esbuild");
  if (!fs.existsSync(pkg)) {
    console.log("installing esbuild into", tools);
    const npm = process.platform === "win32" ? "npm.cmd" : "npm";
    execFileSync(npm, ["install", "--prefix", tools, "--no-save", "--no-audit", "--no-fund", "esbuild@0.25.10"], {
      stdio: "inherit",
      shell: process.platform === "win32",
    });
  }
  return require(pkg);
}

// One small mount file per demo. It clears the host's fallback (a still of
// the demo, shown without JavaScript) and renders the real component there.
function mountFile(slug, name) {
  return [
    `// GENERATED by build-demos.cjs. Mounts the real ${name} into its page.`,
    `import { createRoot } from "react-dom/client";`,
    `import { ${name} } from "./components/${name}";`,
    ``,
    `const host = document.querySelector('[data-demo="${slug}"]');`,
    `if (host) {`,
    `  host.textContent = "";`,
    `  createRoot(host).render(<${name} />);`,
    `  host.setAttribute("data-demo-ready", "1");`,
    `}`,
    ``,
  ].join("\n");
}

async function bundle() {
  const { build } = esbuild();
  fs.mkdirSync(OUT, { recursive: true });
  for (const [slug, name] of Object.entries(DEMOS)) {
    const entry = path.join(WORK, `${slug}.tsx`);
    fs.writeFileSync(entry, mountFile(slug, name));
    const outfile = path.join(OUT, `${slug}.js`);
    await build({
      entryPoints: [entry],
      bundle: true,
      minify: true,
      format: "iife",
      jsx: "automatic",
      target: "es2020",
      define: { "process.env.NODE_ENV": '"production"' },
      outfile,
      logLevel: "warning",
      // React resolves from the app's own node_modules.
      nodePaths: [path.join(REPO, "node_modules")],
    });
    console.log("bundled", slug, (fs.statSync(outfile).size / 1024).toFixed(0) + " KB");
  }
}

/* ---- 3. styles ----------------------------------------------------------- */

// The part of Tailwind's preflight the demos rely on, scoped to the demo so
// it cannot touch the rest of the page. It comes before the utilities, so a
// utility with the same specificity still wins.
const SCOPED_RESET = `
/* The app's theme defines its fonts through two variables that next/font
   sets on the real site. The theme block redeclares --font-sans and
   --font-mono at :root in terms of them, so they must exist at :root too:
   left undefined, the whole page's font stack becomes invalid and falls back
   to the browser's serif. */
:root {
  --font-inter: "Inter";
  --font-mono-face: "JetBrains Mono";
}
[data-demo] {
  font-family: var(--font-sans);
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
}
[data-demo] :where(*, ::before, ::after) {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  border: 0 solid;
}
[data-demo] :where(h1, h2, h3, h4, h5, h6) {
  font-size: inherit;
  font-weight: inherit;
}
[data-demo] :where(ol, ul, menu) {
  list-style: none;
}
[data-demo] :where(img, svg, video, canvas) {
  display: block;
  vertical-align: middle;
}
[data-demo] :where(button, input, select, optgroup, textarea) {
  font: inherit;
  font-feature-settings: inherit;
  letter-spacing: inherit;
  color: inherit;
  border-radius: 0;
  background-color: transparent;
  opacity: 1;
}
[data-demo] :where(button, [role="button"]) {
  cursor: pointer;
}
[data-demo] :where(table) {
  border-collapse: collapse;
  text-indent: 0;
  border-color: inherit;
}
[data-demo] :where(a) {
  color: inherit;
  text-decoration: inherit;
}
`;

async function styles() {
  // Resolved the way Node resolves them from the app, so packages that only
  // declare "exports" load correctly.
  const postcss = require(require.resolve("postcss", { paths: [REPO] }));
  const tailwind = require(require.resolve("@tailwindcss/postcss", { paths: [REPO] }));

  // The app's own theme block, so every colour, font and breakpoint token the
  // demos name resolves to the site's value.
  const globals = fs.readFileSync(path.join(REPO, "src", "app", "globals.css"), "utf8");
  const at = globals.indexOf("@theme {");
  const theme = globals.slice(at, globals.indexOf("\n}", at) + 2);

  // Utilities are emitted unlayered on purpose: the landing stylesheet's
  // element rules (p, ul, h3...) are unlayered too, and a layered utility
  // would lose to them regardless of specificity.
  const input = [
    "/* GENERATED by build-demos.cjs: the Tailwind utilities the site's demos use. */",
    '@import "tailwindcss/theme.css";',
    '@source "./components";',
    theme,
    SCOPED_RESET,
    "@tailwind utilities;",
    "",
  ].join("\n");
  const inputFile = path.join(WORK, "demos.css");
  fs.writeFileSync(inputFile, input);
  const result = await postcss([tailwind({ base: WORK, optimize: { minify: true } })]).process(input, {
    from: inputFile,
    to: path.join(OUT, "demos.css"),
  });
  fs.writeFileSync(path.join(OUT, "demos.css"), result.css);
  console.log("styles", (result.css.length / 1024).toFixed(0) + " KB");
}

(async () => {
  copySources();
  await bundle();
  await styles();
})().catch((e) => {
  console.error("FAIL", e);
  process.exit(1);
});
